import 'package:meta/meta.dart';

/// The kind of challenge Butty can present to the learner.
enum ChallengeType {
  /// Draw or write the glyph that corresponds to a romanized syllable.
  writeCharacter,

  /// Identify which romanized syllable matches the shown Baybayin glyph.
  identifyCharacter,

  /// Translate a short Baybayin word into Filipino/Tagalog.
  translateWord,
}

/// A single Baybayin learning challenge generated by the cloud AI.
@immutable
class BaybayinChallenge {
  const BaybayinChallenge({
    required this.type,
    required this.prompt,
    required this.answer,
    this.targetGlyph,
    this.hint,
  });

  /// What kind of task the learner should perform.
  final ChallengeType type;

  /// The instruction shown to the learner (e.g. "Draw the character for 'ka'").
  final String prompt;

  /// The correct answer (romanized syllable, glyph, or word).
  final String answer;

  /// The Baybayin glyph relevant to this challenge, if applicable.
  final String? targetGlyph;

  /// Optional one-line hint shown after a wrong attempt.
  final String? hint;
}
